export const module2 = {
  id:'module-2',number:'02',title:'Vectors & formulas',
  description:'Calculate with vectors, use sum(), mean() and round(), and select values by position or condition.',
  lessons:[
    {
      id:'vectors',title:'One object, many values',heading:'Calculate once. Apply it to many.',
      intro:'A policy may offer different payment amounts, run over several years or target different income groups. For example, we can compare monthly UBI increases of $100, $125 and $150 using a vector.',
      section:'Create and calculate with vectors',
      body:'<p>A vector is an ordered collection of values. Use <code>c()</code> to combine them, separated by commas. Multiplying a numeric vector by 12 multiplies <em>every element</em> by 12. Use <code>length()</code> to count elements.</p><p>A colon creates consecutive integers: <code>1:4</code> gives 1, 2, 3, 4. In the example below, these are the first four years of a policy.</p><p>Use <code>seq(from = 0, to = 100, by = 25)</code> for a different step size. Here <code>from</code> sets the starting value, <code>to</code> the end of the sequence and <code>by</code> the step size. The result is 0, 25, 50, 75, 100: five possible monthly payment levels.</p>',
      example:'# Compare three monthly UBI increases\nmonthly <- c(100, 125, 150)\nannual <- monthly * 12\nannual\nlength(annual)\n\n# Create a vector for policy years 1 to 4\nyears <- 1:4\nyears\n\n# Create payment levels in steps of 25\npayment_levels <- seq(from = 0, to = 100, by = 25)\npayment_levels',
      noteTitle:'Order matters.',note:'The first annual amount corresponds to the first monthly amount. R calculates element by element. Use equally sized vectors when matching different groups; shorter vectors can otherwise be recycled.',
      taskTitle:'Create payment and year vectors',task:'<ol><li>Create <code>monthly</code> with values <strong>80, 100 and 120</strong>, in that order. Save the corresponding annual amounts as <code>annual</code> and display them.</li><li>Use <code>:</code> to create <code>years</code> with the values <strong>1, 2, 3, 4, 5</strong>, then display it.</li><li>Use <code>seq()</code> to create <code>payment_levels</code> from <strong>50 to 150 in steps of 25</strong>, then display it.</li></ol>',
      starter:'monthly <- c(______)\nannual <- ______\nannual\n\n# Policy years 1 to 5\nyears <- ______\nyears\n\n# Payment levels from 50 to 150 in steps of 25\npayment_levels <- seq(from = ______, to = ______, by = ______)\npayment_levels',
      solution:'monthly <- c(80, 100, 120)\nannual <- monthly * 12\nannual\n\nyears <- 1:5\nyears\n\npayment_levels <- seq(from = 50, to = 150, by = 25)\npayment_levels',
      hints:['Use c(80, 100, 120) for the monthly amounts and multiply monthly by 12. For consecutive years, use a colon between the first and last year: 1:5.', 'For payment_levels, set from = 50, to = 150 and by = 25. The vector should contain 50, 75, 100, 125 and 150.'],
      check:'exists("monthly", inherits=FALSE) && exists("annual", inherits=FALSE) && exists("years", inherits=FALSE) && exists("payment_levels", inherits=FALSE) && isTRUE(all.equal(monthly, c(80,100,120))) && isTRUE(all.equal(annual, c(960,1200,1440))) && isTRUE(all.equal(years, 1:5)) && isTRUE(all.equal(payment_levels, c(50,75,100,125,150)))',success:'Correct: the annual amounts are $960, $1,200 and $1,440; the years run from 1 to 5; and the payment levels are 50, 75, 100, 125 and 150. You have created vectors with c(), : and seq().',
    },
    {
      id:'summaries',title:'Use built-in functions',heading:'Sum, average and round values.',
      intro:'R already has commands for many common calculations. Use its built-in functions to add payment amounts, calculate their average and round a result.',
      section:'Give a function an input',
      body:'<p>A function carries out a named operation. Write its name followed by parentheses containing the input: <code>sum(payments)</code> applies <code>sum()</code> to the values in <code>payments</code>. You can use these built-in functions without having to write them yourself.</p><p><code>sum(payments)</code> adds all the values contained in <code>payments</code>. <code>mean(payments)</code> calculates their arithmetic average: the sum divided by the number of values.</p><p><code>round(average_payment, digits = 2)</code> rounds a value to two decimal places.</p><p>The inputs inside parentheses are called <strong>arguments</strong>. A comma separates them: here the first is the number to round, and <code>digits = 2</code> specifies how many decimal places to keep.</p>',
      example:'payments <- c(100, 125, 140)\n\n# Add the three payments with sum()\ntotal_payment <- sum(payments)\ntotal_payment\n\n# Check the sum manually: the result is the same\n100 + 125 + 140\n\n# Calculate their arithmetic average with mean()\naverage_payment <- mean(payments)\naverage_payment\n\n# Check the average manually\n(100 + 125 + 140) / 3\n\n# Round the average to two decimal places\nrounded_average <- round(average_payment, digits = 2)\nrounded_average',
      noteTitle:'Keep the original value for later calculations.',note:'The total is 365 and the average is about 121.6667. round() returns 121.67, which we save separately as rounded_average. The value stored in average_payment stays unchanged.',
      taskTitle:'Summarise three payments',task:'<p>For payments of <strong>80, 100 and 125</strong>, use <code>sum()</code> to calculate <code>total_payment</code> and <code>mean()</code> to calculate <code>average_payment</code>. Then use <code>round()</code> to save the average rounded to <strong>two decimal places</strong> as <code>rounded_average</code>. Display all three results.</p>',
      starter:'payments <- c(80, 100, 125)\n\ntotal_payment <- ______\naverage_payment <- ______\nrounded_average <- ______\n\ntotal_payment\naverage_payment\nrounded_average',
      solution:'payments <- c(80, 100, 125)\ntotal_payment <- sum(payments)\naverage_payment <- mean(payments)\nrounded_average <- round(average_payment, digits = 2)\ntotal_payment\naverage_payment\nrounded_average',
      hints:['Pass payments to sum() for the total and to mean() for the average.', 'Use round(average_payment, digits = 2) and store this separately as rounded_average.'],
      check:'exists("total_payment", inherits=FALSE) && exists("average_payment", inherits=FALSE) && exists("rounded_average", inherits=FALSE) && isTRUE(all.equal(total_payment, 305)) && isTRUE(all.equal(average_payment, 305/3)) && isTRUE(all.equal(rounded_average, 101.67))',success:'Correct: the total is 305, the average is about 101.6667 and the rounded average is 101.67. You have used sum(), mean() and round().',
      mistakes:[{when:'exists("average_payment", inherits=FALSE) && isTRUE(all.equal(average_payment, 101.67))',message:'Keep the full mean in average_payment. Save the rounded value separately as rounded_average.'}],
      followUp:{
        title:'Combine functions',
        body:'<p>You can use the result of one function as the input to another. Read <code>round(mean(payments), digits = 2)</code> from the inside out: R first calculates <code>mean(payments)</code>, then rounds that result to two decimal places. This combines the two steps from your exercise in a single line.</p>',
        example:'payments <- c(80, 100, 125)\n\n# Calculate the mean, then round it: 101.67\nround(mean(payments), digits = 2)',
      },
    },
    {
      id:'selection',title:'Selecting elements',heading:'Ask a vector a question.',
      intro:'Which income values are above a threshold? A logical condition creates a TRUE/FALSE answer for every element.',
      section:'Use square brackets to select',
      body:'<p><code>income[1]</code> selects the first element. Note that R starts counting at 1.</p><p>You can also select several values at once by putting a vector of positions inside the brackets. <code>income[c(1:3)]</code> selects positions 1, 2 and 3: the first three income values.</p><p><code>income &gt;= 40000</code> compares each value with 40,000 and returns <code>TRUE</code> or <code>FALSE</code> for each value. <code>income[income &gt;= 40000]</code> keeps the values for which the condition is <code>TRUE</code>.</p><p><code>==</code> tests equality; <code>!=</code> tests inequality. <code>%in%</code> checks membership, for example <code>age %in% 20:23</code>.</p>',
      example:'income <- c(20000, 35000, 50000, 80000)\n\n# Select the first value\nincome[1]\n\n# Select several values: positions 1, 2 and 3\nincome[c(1:3)]\n\n# Test one condition, then select the matching incomes\nincome >= 40000\nincome[income >= 40000]',
      noteTitle:'A condition is itself a vector.',note:'The condition returns FALSE, FALSE, TRUE, TRUE. These logical values line up with the original incomes, so the brackets keep 50,000 and 80,000.',
      followUp:{
        position:'before-exercise',
        title:'Combine conditions',
        body:'<p>Use <code>&amp;</code> for “and” when <strong>both conditions must hold for the same value</strong>. For example, <code>income &gt;= 30000 &amp; income &lt; 80000</code> checks that an income is at least 30,000 and strictly below 80,000. Put the combined condition inside square brackets to select those incomes.</p><p>Use <code>|</code> for “or” when <strong>at least one condition must hold</strong>. For example, <code>income &lt; 30000 | income &gt;= 80000</code> identifies incomes outside that interval.</p>',
        example:'income <- c(20000, 35000, 50000, 80000)\n\n# Combine two conditions: both must hold for each income\nincome >= 30000 & income < 80000\nincome[income >= 30000 & income < 80000]',
        note:'The combined condition returns FALSE, TRUE, TRUE, FALSE. The brackets keep 35,000 and 50,000. The value 80,000 is excluded because the second condition uses a strict less-than sign.',
      },
      taskTitle:'Select by position and by condition',task:'<ol><li>Select the <strong>first three values</strong> from <code>income</code> using their positions. Store them as <code>first_three</code> and display them.</li><li>From the same income vector, select values <strong>at least 30,000 and strictly below 80,000</strong>. Both conditions must hold: combine them with <code>&amp;</code> inside the square brackets. Store the selected vector as <code>middle_income</code> and display it.</li></ol>',
      starter:'income <- c(20000, 30000, 50000, 80000, 120000)\n\n# Select the first three values by position\nfirst_three <- income[______]\nfirst_three\n\n# Select values that meet both conditions\nmiddle_income <- income[______]\nmiddle_income',
      solution:'income <- c(20000, 30000, 50000, 80000, 120000)\nfirst_three <- income[c(1:3)]\nfirst_three\n\nmiddle_income <- income[income >= 30000 & income < 80000]\nmiddle_income',
      hints:['For first_three, put c(1:3) inside the square brackets to select positions 1, 2 and 3.', 'For middle_income, use income >= 30000 & income < 80000 inside the square brackets.'],
      check:'exists("first_three", inherits=FALSE) && exists("middle_income", inherits=FALSE) && isTRUE(all.equal(first_three, c(20000,30000,50000))) && isTRUE(all.equal(middle_income, c(30000,50000)))',success:'Correct: positions 1–3 give 20,000, 30,000 and 50,000. The combined conditions select 30,000 and 50,000; the strict upper bound excludes 80,000.',
    },
  ],
};
